# Dissecar uma variável
valor = input('Digite algo: ')
print('O tipo desse valor é: ', type(valor))
print('Só tem espaços? ', valor.isspace())
print('É um número? ', valor.isnumeric())
print('É alfabético? ', valor.isalpha())
print('É alfanumperico? ', valor.isalnum())
print('Está em maiúsculas? ', valor.isupper())
print('Está em minúsculas? ', valor.islower())
print('Está capitalizada? ', valor.istitle())
