# Analisador de Textos
nome = str(input('Digite seu nome completo: ')).strip()
maiu = nome.upper()
minu = nome.lower()
tam = len(nome)
print('Seu nome em maiúsculas é: {}'.format(maiu))
print('Seu nome em minúsculas é: {}'.format(minu))
print('Seu nome tem ao todo: {} letras'.format(tam - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
